#!/usr/bin/env python3
#
# app/services/caddyfile_manager.py
# Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
#

from __future__ import annotations

import asyncio
import hashlib
import logging
import os
from contextlib import asynccontextmanager

try:
    import fcntl
except ImportError:
    fcntl = None  # type: ignore[assignment]
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config.settings import get_settings
from app.models.entities import (
    CaddyBuddyState,
    CaddyConfigVersion,
    CaddySyncEvent,
    CaddyfileSnapshot,
)
from app.repositories.sites import DuplicateSiteError, site_repository
from app.services.caddy import CaddyAdminClient, CaddyServiceError, caddy_service
from app.services.runtime_settings import get_caddy_config
from app.utils.caddyfile import build_domain_site_preview, parse_caddyfile


MANAGED_CADDYFILE_MARKER = "### MANAGED BY CADDYBUDDY ###"
_MANAGED_NOTICE = (
    "# Do not edit this file manually.\n"
    "# Configuration is managed by CaddyBuddy and persisted in SQLite.\n"
)
_STATE_KEY_GLOBAL_CADDYFILE = "global_caddyfile"
_STATE_KEY_LAST_ERROR = "last_error"
_STATE_KEY_LAST_SYNCED_CONFIG_SHA256 = "last_synced_config_sha256"
_STATE_KEY_ORIGINAL_CADDYFILE_SHA256 = "original_caddyfile_sha256"
_STATE_KEY_ONBOARDING_STATUS = "onboarding_status"
_STATE_KEY_RENDERED_CONFIG_SHA256 = "rendered_config_sha256"
_STATE_KEY_SNAPSHOT_SHA256 = "snapshot_sha256"
_EMPTY_CADDY_CONFIG = {"apps": {}}
_STATUS_MANAGED = "managed"
_STATUS_ONBOARDING_FAILED = "onboarding_failed"
_OPERATION_LOCK: asyncio.Lock | None = None
logger = logging.getLogger(__name__)


@dataclass(slots=True)
class CaddyRuntimeStatus:
    managed: bool
    onboarding_required: bool
    caddyfile_path: str
    caddyfile_marker_present: bool
    admin_api_reachable: bool
    last_synced_config_sha256: str | None
    error: str | None = None


@dataclass(slots=True)
class CaddyOnboardingResult:
    status: str
    snapshot_sha256: str | None = None
    synced: bool = False
    error: str | None = None
    error_code: str | None = None


@dataclass(slots=True)
class CaddySyncResult:
    status: str
    config_sha256: str | None = None
    synced: bool = False
    error: str | None = None
    error_code: str | None = None


def _get_operation_lock() -> asyncio.Lock:
    global _OPERATION_LOCK
    if _OPERATION_LOCK is None:
        _OPERATION_LOCK = asyncio.Lock()
    return _OPERATION_LOCK


async def _get_caddyfile_path(session: AsyncSession) -> Path | None:
    config = await get_caddy_config(session)
    return config.caddyfile_path


def _marker_text() -> str:
    return f"{MANAGED_CADDYFILE_MARKER}\n{_MANAGED_NOTICE}"


def _has_managed_marker(caddyfile: str) -> bool:
    for line in caddyfile.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        return stripped == MANAGED_CADDYFILE_MARKER
    return False


def _sha256_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _sync_lock_path() -> Path:
    settings = get_settings()
    return settings.data_dir / ".caddybuddy.caddy.lock"


@asynccontextmanager
async def _acquire_operation_guard():
    lock_path = _sync_lock_path()
    await asyncio.to_thread(lock_path.parent.mkdir, parents=True, exist_ok=True)

    async with _get_operation_lock():
        if fcntl is None:
            # Windows: rely on asyncio lock only
            yield
            return

        lock_file = await asyncio.to_thread(lock_path.open, "a+b")
        try:
            await asyncio.to_thread(fcntl.flock, lock_file.fileno(), fcntl.LOCK_EX)
            yield
        finally:
            await asyncio.to_thread(fcntl.flock, lock_file.fileno(), fcntl.LOCK_UN)
            await asyncio.to_thread(lock_file.close)


def _error_message(error_code: str) -> str:
    messages = {
        "caddyfile_path_not_configured": "Caddyfile path is not configured.",
        "caddyfile_missing": "Caddyfile missing at the configured settings path.",
        "caddyfile_not_regular": "Caddyfile path is not a regular file.",
        "caddyfile_not_readable": "Caddyfile is not readable. Check Docker Compose volume permissions.",
        "caddyfile_not_writable": "Caddyfile is not writable. Check Docker Compose volume permissions.",
        "caddyfile_replace_failed": "Failed to replace Caddyfile with managed marker.",
        "caddy_admin_unavailable": "Caddy Admin API unavailable.",
        "caddy_config_invalid": "Rendered Caddy configuration is invalid.",
        "onboarding_required": "Caddy onboarding is required before synchronization.",
    }
    return messages.get(error_code, error_code)


def _inspect_caddyfile_sync(path: Path | None) -> tuple[str | None, str | None, bool]:
    if path is None:
        return "caddyfile_path_not_configured", None, False
    if not path.exists():
        return "caddyfile_missing", None, False
    if not path.is_file():
        return "caddyfile_not_regular", None, False

    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "caddyfile_not_readable", None, False

    marker_present = _has_managed_marker(content)

    # Use actual open probe instead of os.access() for reliable Docker/ACL detection
    try:
        with path.open("r+", encoding="utf-8"):
            pass
    except OSError:
        logger.warning(
            "Caddyfile not writable: path=%s uid=%s gid=%s mode=%s",
            path,
            os.getuid() if hasattr(os, "getuid") else "unknown",
            os.getgid() if hasattr(os, "getgid") else "unknown",
            oct(path.stat().st_mode & 0o777),
        )
        return "caddyfile_not_writable", content, marker_present

    return None, content, marker_present


async def _inspect_caddyfile(session: AsyncSession) -> tuple[str | None, str | None, bool]:
    path = await _get_caddyfile_path(session)
    return await asyncio.to_thread(_inspect_caddyfile_sync, path)


async def _get_state_value(session: AsyncSession, key: str) -> str | None:
    state = await session.get(CaddyBuddyState, key)
    if state is None or not state.value:
        return None
    return state.value


async def _set_state_value(session: AsyncSession, key: str, value: str) -> None:
    state = await session.get(CaddyBuddyState, key)
    if state is None:
        session.add(CaddyBuddyState(key=key, value=value))
        return
    state.value = value


async def _clear_state_value(session: AsyncSession, key: str) -> None:
    state = await session.get(CaddyBuddyState, key)
    if state is not None:
        await session.delete(state)


async def _ensure_snapshot(
    session: AsyncSession,
    *,
    content: str,
    sha256: str,
    source_path: str,
) -> CaddyfileSnapshot:
    result = await session.execute(
        select(CaddyfileSnapshot).where(CaddyfileSnapshot.sha256 == sha256)
    )
    snapshot = result.scalar_one_or_none()
    if snapshot is not None:
        return snapshot

    snapshot = CaddyfileSnapshot(
        content=content,
        sha256=sha256,
        source_path=source_path,
        imported_by="onboarding",
    )
    session.add(snapshot)
    await session.flush()
    return snapshot


async def _ensure_config_version(
    session: AsyncSession,
    *,
    rendered_config: str,
    sha256: str,
) -> CaddyConfigVersion:
    result = await session.execute(
        select(CaddyConfigVersion).where(CaddyConfigVersion.sha256 == sha256)
    )
    version = result.scalar_one_or_none()
    if version is not None:
        return version

    version = CaddyConfigVersion(rendered_config=rendered_config, sha256=sha256)
    session.add(version)
    await session.flush()
    return version


def _record_sync_event(
    session: AsyncSession,
    *,
    status: str,
    config_sha256: str | None = None,
    error: str | None = None,
) -> None:
    session.add(
        CaddySyncEvent(
            status=status,
            config_sha256=config_sha256,
            error=error,
        )
    )


def replace_caddyfile_with_marker(path: Path) -> None:
    marker = _marker_text()
    with path.open("r+", encoding="utf-8") as handle:
        handle.seek(0)
        handle.write(marker)
        handle.truncate()
        handle.flush()
        os.fsync(handle.fileno())

    dir_fd = os.open(path.parent, os.O_RDONLY)
    try:
        os.fsync(dir_fd)
    finally:
        os.close(dir_fd)


async def get_baseline_caddyfile(session: AsyncSession) -> str:
    return await _get_state_value(session, _STATE_KEY_GLOBAL_CADDYFILE) or ""


async def set_baseline_caddyfile(session: AsyncSession, caddyfile: str) -> None:
    await _set_state_value(session, _STATE_KEY_GLOBAL_CADDYFILE, caddyfile)
    await session.flush()


async def _admin_api_reachable(session: AsyncSession) -> bool:
    config = await get_caddy_config(session)
    settings = get_settings()
    try:
        async with CaddyAdminClient(
            config.admin_url,
            settings.caddy_admin_timeout_seconds,
        ) as client:
            return await client.health()
    except (CaddyServiceError, OSError, ValueError):
        return False


async def get_caddy_runtime_status(session: AsyncSession) -> CaddyRuntimeStatus:
    path = await _get_caddyfile_path(session)
    file_error, _content, marker_present = await _inspect_caddyfile(session)
    admin_api_reachable = await _admin_api_reachable(session)
    last_synced_config_sha256 = await _get_state_value(session, _STATE_KEY_LAST_SYNCED_CONFIG_SHA256)
    persisted_error = await _get_state_value(session, _STATE_KEY_LAST_ERROR)
    error = file_error or persisted_error

    return CaddyRuntimeStatus(
        managed=marker_present,
        onboarding_required=file_error is None and not marker_present,
        caddyfile_path=str(path) if path is not None else "",
        caddyfile_marker_present=marker_present,
        admin_api_reachable=admin_api_reachable,
        last_synced_config_sha256=last_synced_config_sha256,
        error=error,
    )


def _render_generated_site_block(site) -> str:
    return build_domain_site_preview(
        name=site.domain,
        upstream=site.upstream_url.strip() if site.upstream_url else None,
        caddy_directives=site.caddy_directives,
        ssl_enabled=True,
    )


async def build_full_caddyfile(session: AsyncSession) -> str:
    """Build the final Caddyfile from SQLite state only."""
    parts: list[str] = []

    baseline = (await get_baseline_caddyfile(session)).strip()
    if baseline:
        parts.append(baseline)

    sites = await site_repository.list_all(session, enabled_only=True)
    for site in sorted(sites, key=lambda item: item.domain):
        parts.append(_render_generated_site_block(site))

    return "\n\n".join(parts)


async def _sync_caddy_configuration_locked(
    session: AsyncSession,
    *,
    force: bool = False,
    require_marker: bool = True,
) -> CaddySyncResult:
    status = await get_caddy_runtime_status(session)
    if require_marker and not status.caddyfile_marker_present:
        return CaddySyncResult(
            status="onboarding_required",
            error=_error_message("onboarding_required"),
            error_code="onboarding_required",
        )
    if not status.admin_api_reachable:
        await _set_state_value(session, _STATE_KEY_LAST_ERROR, "caddy_admin_unavailable")
        _record_sync_event(
            session,
            status="sync_failed",
            error=_error_message("caddy_admin_unavailable"),
        )
        return CaddySyncResult(
            status="admin_api_unavailable",
            error=_error_message("caddy_admin_unavailable"),
            error_code="caddy_admin_unavailable",
        )

    rendered_config = await build_full_caddyfile(session)
    rendered_config_sha256 = _sha256_text(rendered_config)
    await _set_state_value(session, _STATE_KEY_RENDERED_CONFIG_SHA256, rendered_config_sha256)
    version = await _ensure_config_version(
        session,
        rendered_config=rendered_config,
        sha256=rendered_config_sha256,
    )
    last_synced_config_sha256 = await _get_state_value(session, _STATE_KEY_LAST_SYNCED_CONFIG_SHA256)

    if not force and rendered_config_sha256 == last_synced_config_sha256:
        await _clear_state_value(session, _STATE_KEY_LAST_ERROR)
        _record_sync_event(
            session,
            status="no_change",
            config_sha256=rendered_config_sha256,
        )
        return CaddySyncResult(
            status="no_change",
            config_sha256=rendered_config_sha256,
            synced=False,
        )

    await session.flush()

    if rendered_config.strip():
        try:
            config_payload = await caddy_service.adapt_caddyfile_to_json(rendered_config)
        except CaddyServiceError as exc:
            await _set_state_value(session, _STATE_KEY_LAST_ERROR, "caddy_config_invalid")
            _record_sync_event(
                session,
                status="validation_failed",
                config_sha256=rendered_config_sha256,
                error=str(exc),
            )
            return CaddySyncResult(
                status="validation_failed",
                config_sha256=rendered_config_sha256,
                error=str(exc),
                error_code="caddy_config_invalid",
            )
    else:
        config_payload = _EMPTY_CADDY_CONFIG

    config = await get_caddy_config(session)
    settings = get_settings()
    try:
        async with CaddyAdminClient(
            config.admin_url,
            settings.caddy_admin_timeout_seconds,
        ) as client:
            await client.load_config(config_payload)
    except (CaddyServiceError, ValueError) as exc:
        await _set_state_value(session, _STATE_KEY_LAST_ERROR, "caddy_admin_unavailable")
        _record_sync_event(
            session,
            status="sync_failed",
            config_sha256=rendered_config_sha256,
            error=str(exc),
        )
        return CaddySyncResult(
            status="sync_failed",
            config_sha256=rendered_config_sha256,
            error=str(exc),
            error_code="caddy_admin_unavailable",
        )

    version.synced_at = datetime.now(UTC)
    await _set_state_value(session, _STATE_KEY_LAST_SYNCED_CONFIG_SHA256, rendered_config_sha256)
    await _clear_state_value(session, _STATE_KEY_LAST_ERROR)
    _record_sync_event(
        session,
        status="synced",
        config_sha256=rendered_config_sha256,
    )
    return CaddySyncResult(
        status="synced",
        config_sha256=rendered_config_sha256,
        synced=True,
    )


async def sync_caddy_configuration(
    session: AsyncSession,
    *,
    force: bool = False,
) -> CaddySyncResult:
    async with _acquire_operation_guard():
        return await _sync_caddy_configuration_locked(session, force=force)


async def onboard_caddy(session: AsyncSession) -> CaddyOnboardingResult:
    path = await _get_caddyfile_path(session)
    async with _acquire_operation_guard():
        file_error, content, marker_present = await _inspect_caddyfile(session)
        if marker_present:
            return CaddyOnboardingResult(status="already_managed", synced=False)
        if file_error is not None:
            await _set_state_value(session, _STATE_KEY_LAST_ERROR, file_error)
            await _set_state_value(session, _STATE_KEY_ONBOARDING_STATUS, _STATUS_ONBOARDING_FAILED)
            return CaddyOnboardingResult(
                status="error",
                error=_error_message(file_error),
                error_code=file_error,
            )
        if content is None or path is None:
            await _set_state_value(session, _STATE_KEY_LAST_ERROR, "caddyfile_missing")
            await _set_state_value(session, _STATE_KEY_ONBOARDING_STATUS, _STATUS_ONBOARDING_FAILED)
            return CaddyOnboardingResult(
                status="error",
                error=_error_message("caddyfile_missing"),
                error_code="caddyfile_missing",
            )
        if not await _admin_api_reachable(session):
            await _set_state_value(session, _STATE_KEY_LAST_ERROR, "caddy_admin_unavailable")
            await _set_state_value(session, _STATE_KEY_ONBOARDING_STATUS, _STATUS_ONBOARDING_FAILED)
            _record_sync_event(
                session,
                status=_STATUS_ONBOARDING_FAILED,
                error=_error_message("caddy_admin_unavailable"),
            )
            return CaddyOnboardingResult(
                status="error",
                error=_error_message("caddy_admin_unavailable"),
                error_code="caddy_admin_unavailable",
            )

        snapshot_sha256 = _sha256_text(content)
        await _ensure_snapshot(
            session,
            content=content,
            sha256=snapshot_sha256,
            source_path=str(path),
        )

        # Parse Caddyfile and import sites
        parsed = parse_caddyfile(content)
        imported_count = 0
        skipped_count = 0
        for domain, directives in parsed.sites:
            try:
                await site_repository.create(
                    session,
                    domain=domain,
                    caddy_directives=directives,
                    enabled=True,
                )
                imported_count += 1
                logger.info("Imported site from Caddyfile: %s", domain)
            except DuplicateSiteError:
                skipped_count += 1
                logger.warning("Site already exists, skipping: %s", domain)
            except ValueError as exc:
                skipped_count += 1
                logger.warning("Failed to import site %s: %s", domain, exc)

        # Log import summary
        global_block_lines = len(parsed.global_block.strip().splitlines()) if parsed.global_block.strip() else 0
        logger.info(
            "Caddyfile parsed: imported=%d sites, skipped=%d, global_block=%d lines, snippets=%d",
            imported_count,
            skipped_count,
            global_block_lines,
            len(parsed.snippets),
        )

        # Store only the global block (without sites) as baseline
        baseline = parsed.global_block.strip() if parsed.global_block else ""
        await set_baseline_caddyfile(session, baseline)

        await _set_state_value(session, _STATE_KEY_ORIGINAL_CADDYFILE_SHA256, snapshot_sha256)
        await _set_state_value(session, _STATE_KEY_SNAPSHOT_SHA256, snapshot_sha256)
        await session.flush()

        sync_result = await _sync_caddy_configuration_locked(
            session,
            force=True,
            require_marker=False,
        )
        if sync_result.status not in {"synced", "no_change"}:
            await _set_state_value(session, _STATE_KEY_ONBOARDING_STATUS, _STATUS_ONBOARDING_FAILED)
            _record_sync_event(
                session,
                status=_STATUS_ONBOARDING_FAILED,
                config_sha256=sync_result.config_sha256,
                error=sync_result.error,
            )
            return CaddyOnboardingResult(
                status=_STATUS_ONBOARDING_FAILED,
                snapshot_sha256=snapshot_sha256,
                synced=False,
                error=sync_result.error,
                error_code=sync_result.error_code,
            )

        try:
            await asyncio.to_thread(replace_caddyfile_with_marker, path)
        except OSError:
            await _set_state_value(session, _STATE_KEY_LAST_ERROR, "caddyfile_replace_failed")
            await _set_state_value(session, _STATE_KEY_ONBOARDING_STATUS, _STATUS_ONBOARDING_FAILED)
            _record_sync_event(
                session,
                status=_STATUS_ONBOARDING_FAILED,
                error=_error_message("caddyfile_replace_failed"),
            )
            return CaddyOnboardingResult(
                status="error",
                snapshot_sha256=snapshot_sha256,
                error=_error_message("caddyfile_replace_failed"),
                error_code="caddyfile_replace_failed",
            )

        await _set_state_value(session, _STATE_KEY_ONBOARDING_STATUS, _STATUS_MANAGED)
        await _clear_state_value(session, _STATE_KEY_LAST_ERROR)
        logger.info("Onboarding complete: imported %d sites", imported_count)
        return CaddyOnboardingResult(
            status="onboarded",
            snapshot_sha256=snapshot_sha256,
            synced=sync_result.synced,
        )


async def import_mounted_caddyfile_if_needed(session: AsyncSession) -> bool:
    result = await onboard_caddy(session)
    return result.status == "onboarded"


async def validate_and_deploy_full_caddyfile(session: AsyncSession) -> tuple[bool, str]:
    result = await sync_caddy_configuration(session)
    if result.status == "synced":
        return True, "Configuration deployed successfully"
    if result.status == "no_change":
        return True, "Configuration unchanged"
    return False, result.error or "Caddy configuration sync failed."
