#!/usr/bin/env python3
#
# tools/pyproject-deps.py
# Copyright (C) 2026 Gill-Bates http://github.com/Gill-Bates
#

"""Print one optional dependency group from pyproject.toml for pip consumers.

The documentation toolchain is declared in ``[project.optional-dependencies]``.
CI and Trivy consume a temporary flat requirements file generated by this script.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

_PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def collect(group: str, pyproject: Path) -> list[str]:
    """Return the named optional dependency group from *pyproject*."""
    with pyproject.open("rb") as handle:
        data = tomllib.load(handle)

    extras = data.get("project", {}).get("optional-dependencies", {})
    dependencies = extras.get(group)
    if dependencies is None:
        available = ", ".join(sorted(extras)) or "none"
        raise SystemExit(f"{pyproject}: no optional dependency group {group!r}. Known extras: {available}")
    return list(dependencies)


def main() -> int:
    """Write the requested dependency group to stdout, one requirement per line."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("group", help="optional dependency group to print")
    parser.add_argument(
        "--pyproject",
        type=Path,
        default=_PYPROJECT,
        help=f"path to pyproject.toml (default: {_PYPROJECT})",
    )
    args = parser.parse_args()

    print(*collect(args.group, args.pyproject), sep="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
